//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class autoshopEntities : DbContext
    {
        private static autoshopEntities _context;
        public autoshopEntities()
            : base("name=autoshopEntities")
        {
        }

        public static autoshopEntities GetContext() 
        {
            if (_context == null)
            {
                _context = new autoshopEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<PartCategory> PartCategory { get; set; }
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
